// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HDTPluginTemplate
{
    internal sealed partial class Vsix
    {
        public const string Id = "HDTPluginTemplate.f1645e9e-1e1d-4197-ba4b-9241f931307f";
        public const string Name = "HDTPluginTemplate";
        public const string Description = @"A Simple HDT Plug-in Project Template to help jump start your own creations.";
        public const string Language = "en-US";
        public const string Version = "0.7.1";
        public const string Author = "High Falootin Technology Corporation";
        public const string Tags = "C#, XAML, Hearthstone Deck Tracker, HDT,";
    }
}
