// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HDTPluginTemplate
{
    internal sealed partial class Vsix
    {
        public const string Id = "HDTPluginTemplate.F679548C-9A0F-4CA9-8C51-7661C87A98A9";
        public const string Name = "HDTPluginTemplate";
        public const string Description = @"A Simple Hearthstone Deck Tracker Plug-In Project Template to help jump start your own creations.";
        public const string Language = "en-US";
        public const string Version = "0.7.4";
        public const string Author = "High Falootin Technology Corporation";
        public const string Tags = "C#, XAML, Hearthstone Deck Tracker, HDT,";
    }
}
