// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HDTPluginTemplate
{
    internal sealed partial class Vsix
    {
        public const string Id = "HDTPluginTemplate.75730f20-3245-475e-86db-ae8ad70b82be";
        public const string Name = "HDTPluginTemplate";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alex Pearlstein";
        public const string Tags = "";
    }
}
